# API Gateway Configuration
server:
  port: 8080

spring:
  # Redis configuration for Rate Limiting
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${redis-password:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1

  cloud:
    consul:
      discovery:
        service-name: api-gateway
        instance-id: ${spring.application.name}:${server.port}
        health-check-url: http://host.docker.internal:${server.port}/actuator/health

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Default filters applied to all routes
      default-filters:
        - name: RequestSize
          args:
            maxSize: 5MB

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "${FRONTEND_URL:http://localhost:3000}"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true

# =============================================================================
# Rate Limiting Configuration
# =============================================================================
gateway:
  rate-limit:
    # Default rate limit for general API endpoints
    default:
      replenish-rate: 10      # Requests per second allowed
      burst-capacity: 20       # Maximum burst size
      requested-tokens: 1      # Tokens consumed per request

    # Stricter rate limit for auth endpoints (prevent brute force)
    auth:
      replenish-rate: 5        # Requests per second allowed
      burst-capacity: 10       # Maximum burst size

    # Rate limit key from Vault
    key: ${rate-limit-key:default-key}

# =============================================================================
# Actuator & Monitoring
# =============================================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

# =============================================================================
# Logging
# =============================================================================
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.consul: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.data.redis: DEBUG
