# =============================================================================
# API Gateway - DEVELOPMENT Configuration
# =============================================================================

server:
  port: 8080

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${redis-password:}
      timeout: 2000ms

  cloud:
    consul:
      discovery:
        service-name: api-gateway
        instance-id: ${spring.application.name}:${server.port}
        health-check-url: http://localhost:${server.port}/actuator/health

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://127.0.0.1:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 3600

# Rate Limiting - Relaxed for development
gateway:
  rate-limit:
    default:
      replenish-rate: 100
      burst-capacity: 200
      requested-tokens: 1
    auth:
      replenish-rate: 50
      burst-capacity: 100

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

