# =============================================================================
# API Gateway - PRODUCTION Configuration
# =============================================================================

server:
  port: 8080
  # Production compression
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${redis-password}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
      # Redis Sentinel for HA (optional)
      # sentinel:
      #   master: mymaster
      #   nodes: ${REDIS_SENTINEL_NODES}

  cloud:
    consul:
      discovery:
        service-name: api-gateway
        instance-id: ${spring.application.name}:${random.uuid}
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
        health-check-critical-timeout: 60s

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Production CORS - Strict
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "${FRONTEND_URL}"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - Authorization
              - Content-Type
              - X-Requested-With
              - X-Request-ID
            exposed-headers:
              - X-Request-ID
              - X-RateLimit-Remaining
            allow-credentials: true
            max-age: 7200

      # Production timeouts
      httpclient:
        connect-timeout: 5000
        response-timeout: 30000

# Rate Limiting - Strict for production
gateway:
  rate-limit:
    default:
      replenish-rate: 10
      burst-capacity: 20
      requested-tokens: 1
    auth:
      replenish-rate: 5
      burst-capacity: 10

logging:
  level:
    org.springframework.cloud.gateway: WARN

