# =============================================================================
# Auth Service - PRODUCTION Configuration
# =============================================================================

server:
  port: 8088
  servlet:
    context-path: /api/v1
  # Production security settings
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE:classpath:keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/auth_service_db
    username: ${DB_USER:${postgres-user:}}
    password: ${DB_PASSWORD:${postgres-password:}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  cloud:
    consul:
      discovery:
        service-name: auth-service
        instance-id: ${spring.application.name}:${random.uuid}
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/api/v1/actuator/health
        health-check-critical-timeout: 60s

# JWT Configuration - From Vault (REQUIRED)
jwt:
  signer-key: ${JWT_SIGNER_KEY:${jwt-signer-key:}}
  expiration: ${JWT_EXPIRATION:${jwt-expiration:1800}}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:${refresh-token-expiration:43200}}

# SpringDoc OpenAPI - DISABLED in production
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

