# Auth Service Configuration
server:
  port: 8088
  servlet:
    context-path: /api/v1

spring:
  datasource:
    # Credentials from Vault (prod) or env vars (dev)
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/auth_service_db
    username: ${DB_USER:${postgres-user:ecom_admin}}
    password: ${DB_PASSWORD:${postgres-password:}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    consul:
      discovery:
        service-name: auth-service
        instance-id: ${spring.application.name}:${server.port}
        health-check-url: http://host.docker.internal:${server.port}/api/v1/actuator/health

# JWT Configuration - from Vault (prod) or env vars (dev)
jwt:
  signer-key: ${JWT_SIGNER_KEY:${jwt-signer-key:}}
  expiration: ${JWT_EXPIRATION:${jwt-expiration:3600}}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:${refresh-token-expiration:86400}}

# SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
