# Auth Service Configuration
server:
  port: 8088
  servlet:
    context-path: /api/v1

spring:
  datasource:
    # Credentials are now loaded from Vault: secret/ecommerce/database/postgres
    url: ${database.url:jdbc:postgresql://localhost:5432/user_service_db}
    username: ${database.username:admin}
    password: ${database.password:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    consul:
      discovery:
        service-name: auth-service
        instance-id: ${spring.application.name}:${server.port}
        health-check-url: http://host.docker.internal:${server.port}/api/v1/actuator/health

# JWT Configuration - Values loaded from Vault: secret/ecommerce/auth-service
jwt:
  signerKey: ${jwt-signer-key:}
  expiration: ${jwt-expiration:3600}
  refreshExpiration: ${refresh-token-expiration:86400}

# SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
