# =============================================================================
# Auth Service - STAGING Configuration
# =============================================================================

server:
  port: 8088
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/user_service_db
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    consul:
      discovery:
        service-name: auth-service
        instance-id: ${spring.application.name}:${random.uuid}
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/api/v1/actuator/health

# JWT Configuration - From Vault
jwt:
  signerKey: ${jwt-signer-key}
  expiration: ${jwt-expiration:3600}
  refreshExpiration: ${refresh-token-expiration:86400}

# SpringDoc OpenAPI - Enabled but limited in staging
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method

