# =============================================================================
# Auth Service - DEVELOPMENT Configuration
# =============================================================================

server:
  port: 8088
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/user_service_db
    username: ${database.username:ecom_admin}
    password: ${database.password:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cloud:
    consul:
      discovery:
        service-name: auth-service
        instance-id: ${spring.application.name}:${server.port}
        health-check-url: http://localhost:${server.port}/api/v1/actuator/health

# JWT Configuration
jwt:
  signerKey: ${jwt-signer-key:dev-secret-key-for-testing-only-do-not-use-in-production}
  expiration: ${jwt-expiration:3600}
  refreshExpiration: ${refresh-token-expiration:86400}

# SpringDoc OpenAPI - Enabled in dev
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method

# Redis Configuration
spring.data.redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
  timeout: 60000
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
