# =============================================================================
# Auth Service - DEVELOPMENT Configuration
# =============================================================================

server:
  port: 8088
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/auth_service_db
    username: ${DB_USER:ecom_admin}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cloud:
    consul:
      discovery:
        service-name: auth-service
        instance-id: ${spring.application.name}:${server.port}
        health-check-url: http://localhost:${server.port}/api/v1/actuator/health

# JWT Configuration - from .env file (dev)
jwt:
  signer-key: ${JWT_SIGNER_KEY:}
  expiration: ${JWT_EXPIRATION:3600}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400}

# SpringDoc OpenAPI - Enabled in dev
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method

# Health check - disable mail in dev
management:
  health:
    mail:
      enabled: false
