# =============================================================================
# User Service - DEVELOPMENT Configuration
# =============================================================================

server:
  port: 8083
  servlet:
    context-path: /api/v1

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/user_service_db
    username: ${postgres-user:admin}
    password: ${postgres-password:admin123}
    driver-class-name: org.postgresql.Driver

  cloud:
    consul:
      discovery:
        service-name: user-service
        health-check-url: http://localhost:${server.port}/api/v1/actuator/health
        instance-id: ${spring.application.name}:${server.port}

# Service-to-Service Authentication
service:
  auth:
    enabled: true
    client-id: user-service
    client-secret: ${client-secret:}
    auth-service-url: http://localhost:8088/api/v1

# MinIO Configuration for local development
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${minio-access-key:minioadmin}
  secret-key: ${minio-secret-key:minioadmin}
  bucket-name: user-avatars

# Logging - more verbose for development
logging:
  level:
    com.ecommerce.user: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

